### ISSUE TITLE
FR: Circuit Breaker Plugin

### ISSUE THREAD

**Issue by alexleeelkins** [Sammyjo20/Saloon#15]
Hello, love the package!

I think it could be beneficial to have a sensible default (but configurable) circuit breaker pattern plugin available to use (opt in only). A circuit breaker pattern is good for use with external API integrations for multiple reasons: alerts when an external API reaches a failure threshold, preventing subsequent requests for a time period if the external API is known to be down, prevention of further security-type lockouts (if a request is triggering an external API’s request limits, for example).

Is there any interest in this?

Thanks!

**Comment by Wulfheart** [comment]
Any concrete idea how the Saloon API should be?

**Comment by Sammyjo20** [comment]
Thanks @alexleeelkins! 

I like the sound of this. I feel this would work better for the Laravel package of saloon because of the powerful caching and rate limiting you could use there. We could also use a caching plugin like symfony’s one or doctrine? Honestly I don’t have enough experience with caching outside of Laravel. 

You could build this using the interceptors and handlers and the API for those are well documented on the official docs.

**Comment by Sammyjo20** [comment]
Hi Alex, 

Would it be okay if I close this issue for now? 

Sam

**Comment by Sammyjo20** [comment]
Actually, I’ve been thinking about this. What about this?

I think it would be useful to add various hooks into Saloon which can be added which can be useful for logging. For example I could add a hook before a request has happened, after a request has happened, after a successful response and after a failure response. 

This could be added to the connector or the request (or both) and can be used. 

There could also be a shouldSendRequest() which can return false if a provided condition fails

**Comment by Sammyjo20** [comment]
I'm going to close this issue for now, but happy to discuss again soon.
