### ISSUE TITLE
Unable to authenticate a pending request

### ISSUE THREAD

**Issue by Riley19280** [Sammyjo20/Saloon#167]
According to the [docs](https://docs.saloon.dev/digging-deeper/retrying-requests#customising-when-a-retry-is-attempted), I should be able to call 
`$pendingRequest->authenticate(...)` from the retry handler, however it does not seem to be updating the header on the pending request. I have created a reproduction test case [here](https://github.com/Riley19280/Saloon/commit/cd3603d8587406e82961f9aa1f00d424d22b6b86).
```php
test('you can authenticate the pending request inside the retry handler', function () {
    $mockClient = new MockClient([
        MockResponse::make(['name' => 'Sam'], 401),
        MockResponse::make(['name' => 'Gareth'], 200),
    ]);

    $connector = new TestConnector;
    $connector->withMockClient($mockClient);

    $response = $connector->sendAndRetry(new UserRequest, 2, 0, function (Exception $exception, PendingRequest $pendingRequest) {

        $pendingRequest->authenticate(new \Saloon\Http\Auth\TokenAuthenticator('newToken'));

        return true;
    });

    expect($response->status())->toBe(200);
    expect($response->json())->toEqual(['name' => 'Gareth']);
    expect($response->getPendingRequest()->headers()->get('Authorization'))->toEqual('Bearer newToken');
});
```

The test results in `Failed asserting that null matches expected 'Bearer newToken'.`

**Comment by Sammyjo20** [comment]
Hey @Riley19280 ah, this is because you are unable to use the “authenticate” method on a fully constructed PendingRequest. This is because the “set” method of the authenticator is run within a middleware, and PendingRequests run middleware during the constructor.  

I will create an update to the PendingRequest logic which will invoke the authenticator straight away if the PendingRequest is considered “ready”

Something for future consideration though, the sendAndRetry method could pass in an ordinary “request” instead of a pending request when updating. 

Apologies about this, I will look into it!

**Comment by Sammyjo20** [comment]
Alternatively to fix this now, you can add the header directly within that closure.

**Comment by Sammyjo20** [comment]
This should be fixed in https://github.com/Sammyjo20/Saloon/releases/tag/v2.0.1
