### ISSUE TITLE
Casting paginated responses to DTO

### ISSUE THREAD

**Issue by boryn** [Sammyjo20/Saloon#191]
I have a response with `'data'` key, where there are several items. Normally (without automatic pagination), I'm able to get the collection of DTOs based on these suggestions: https://github.com/Sammyjo20/Saloon/discussions/186 using just `$response->dto()`.

Now, I wanted to have the automatic pagination (I use `OffsetPaginator`), so instead of 
```php
$response = $this->connector()->send($this->request);
```
I used:
```php
$paginator = $this->connector()->paginate($this->request);
```

everything is properly configured, as I can run
```php
foreach($paginator as $response) {
    $pageData = $response->json('data');
}
```

as well I may create a collection of individual "raw" items in response: `$paginator->collect('data')`.

I wanted to create DTOs based on the combined paginator results, and tried `$paginator->dto()`, but got: "Call to undefined method OffsetPaginator::dto()"

I know, I can easily build the DTOs manually:
```php
$dtos = $paginator->collect('data')->map(
    fn ($post) =>  PostDto::fromItem($post),
);
```

but it would be nice to have a "helper/shortcut" method `dto()` as with single responses which would use the same `createDtoFromResponse()` method and we could similarly use `$paginator->dto()`.

**Comment by Sammyjo20** [comment]
Hey @boryn thank you for your message 🙌

That's a really great suggestion and I'll put it on my roadmap for future v2 development. The DTO method could simply be a wrapper around the existing iterator which calls `dto` :) 

I'm going to close this for now but please feel free to open a discussion if you have any further ideas.

**Comment by pindab0ter** [comment]
Is there any news on this?

**Comment by pindab0ter** [comment]
I've looked into making this work, and I would like your feedback.

The pagination plugin has functions like `items()` and `collect()`. My thought was to create DTO versions `dtos()` and `collectDtos()`. I had a working prototype up fairly quickly, but ran into the following design problem.

The request class implements a function called `createDtoFromResponse` that returns any kind of `object`, whereas the pagination extension deals with 'items' as members of an array under a key in the response. It's this one/many discrepancy that I would like input on.

It makes sense to have the request decide how to transform any individual response into an array of DTOs. I would like `createDtoFromResponse` to be that place, but I don't think it can be, as it returns a single `object`.

The next best thing would be to make an interface with a method `createDtosFromResponse` that returns `object[]`.

I would like your thoughts @Sammyjo20. Since I need this for a project, I would like to collaborate to make this a part of the pagination plugin in a way that suits not only our but most people's needs.
