### ISSUE TITLE
Add push() option 

### ISSUE THREAD

**Issue by abdevcode** [Sammyjo20/Saloon#223]
Hi!
First of all, I want to thank you for developing this awesome library! :)

My question is about adding a new method to the ArrayStore class to push data when we have multidimensional arrays (e.g. JSON bodies).

The function would be something like this:

```
    /**
     * Push items to the repository.
     *
     * @param string $key
     * @param mixed $value
     * @return $this
     */
    public function push(string $key, mixed $value): static
    {
        $this->data[$key][] = Helpers::value($value);

        return $this;
    }
```

thanks!

**Comment by abdevcode** [comment]
As an example, some APIs accept more than one item for some parameters.
E.g.
```
{
  "participants": [
    {
      "id": "id1",
      "name": "Alice"
    },
    {
      "id": "id2",
      "name": "Bob"
    },
  ]
}
```

**Comment by Sammyjo20** [comment]
Hey @abdevcode 

Many thanks for this idea and I apologise for the delay in replying. 

I love this idea, being able to quickly add to an existing array of data would be really handy, especially when dealing with JSON. 

I will see if I can introduce this method to the ArrayStore but since it has an interface, I don’t think I’ll be able to add the method without a breaking change - that being said I can add this for Saloon v3 which I am currently working on  and won’t be far off from releasing. 

Many thanks!

**Comment by Sammyjo20** [comment]
Hey @abdevcode I'm going to close this issue for now as it's on my roadmap of features to add.
