### ISSUE TITLE
Compatibility between Cache-plugin and the events sent by the Laravel-integration

### ISSUE THREAD

**Issue by carnevalle** [Sammyjo20/Saloon#238]
This issue is with the event SentSaloonRequest sent by the Laravel integration. I am submitting the issue here, as I was bit confused which of the Laravel-packages it was related to. 

The issue is that both the cache-plugin and the laravel-integration prepends the onResponse-middleware, which creates a race condition. I would expect that the Response from the SentSaloonRequest to know if it has been retrieved from the cache, but at the moment it will return `isCached() == false` even though it has been fetched from the cache.

Is there any reason why the middleware sending the event is being prepended?

**Comment by Sammyjo20** [comment]
Hey @carnevalle 

Come to think of it, I can't remember why this is prepended. I think it's because of the `AlwaysThrowExceptions` trait. This, if it runs before the event middleware will throw an exception.

I think it would be useful if the middleware actually ran a little bit later because any changes to the response could be applied to the event.

What are your thoughts?

**Comment by carnevalle** [comment]
I think the best solution would be to not prepend the SentSaloonRequest as this allows us to prepend anything that needs to run before the event is sent.

**Comment by Sammyjo20** [comment]
Hey @carnevalle I agree - but one small issue, the reason I used `prepend` is because if someone is using the `AlwaysThrowOnError` trait, then this will take priority over the ability to fire the event or record the request (For Laravel's recording feature, not fixtures)

I could make the change, I don't suppose it could cause too many issues - because if it's throwing an exception anyway then it shouldn't get to the event?

**Comment by Sammyjo20** [comment]
From v3 there's going to be a feature where you can ask a middleware to run at the end, so the middleware like these will always run at the end of the middleware stack no matter what.

**Comment by Sammyjo20** [comment]
I'm going to close this issue - as from v3 I'm going to implement "final" or "last" middleware that will guarantee to run at the end of a middleware stack, and the Laravel events will be in these last middleware.

**Comment by carnevalle** [comment]
Great job @Sammyjo20
