### ISSUE TITLE
Returning paginator collection when response has no 'data' key

### ISSUE THREAD

**Issue by boryn** [Sammyjo20/Saloon#250]
I make a request to an endpoint, which returns items without the 'data' key, like this:

```
array:5 [
  0 => array:49 [
    "uid" => "bd35d0f4-74bf-4358-989f-640c3e6d0ea9"
    // ...
    ]
  1 => array:49 [
    "uid" => "47f4b591-a892-40de-8dfa-9bc81a85ac0e"
    // ...  
    ]
  2 => array:49 [
    "uid" => "3e5c6f5c-dfab-42ab-baf1-a01b848e4376"
    // ...  
    ]
  3 => array:49 [
    "uid" => "299d660d-70fa-49f8-bf11-2ddef9c1f890"
    // ...  
    ]
  4 => array:49 [
    "uid" => "a377e778-595b-458c-9e28-cb9d365434a7"
    // ...
   ]
]
```

in json it looks like this:
`[{"uid":"bd35d0f4-74bf-4358-989f-640c3e6d0ea9", ...},{"uid":"47f4b591-a892-40de-8dfa-9bc81a85ac0e", ...}]`

When I do:
```php
$collection = $paginator->collect(null, lazy: false);
```

actually I get a collection of `Saloon\Http\Response`s:
![image](https://github.com/Sammyjo20/Saloon/assets/807297/441aeb6f-f910-4e17-b190-695c9dec01d9)

and each of the responses contains a proper `decodedJson` like:
![image](https://github.com/Sammyjo20/Saloon/assets/807297/764ab9b0-5c63-472a-9c74-e4c173fad8aa)

but somehow they are not glued together to create a collection. Tried as well with `collapse: false` - no difference.

I found a workaround for this using custom `resolveResponseClass()` where I "forcefully" wrap the results in the `'data'` key and later do `$paginator->collect('data', lazy: false);` and it works. 

PS. At the regular (without pagination) request, the `->collect(null)` works properly - that is it returns several fetched items in the proper way.

**Comment by juse-less** [comment]
Hi!

This was a deliberate decision when we designed the initial drafts, in order to be able to get the actual responses.
We deemed it easy enough to lazily map the responses to grab the DTOs, that it was worth it.

However, in a hindsight, I think it's better to always resort to grabbing DTOs using `collect()`, which will also be more consistent with the rest of the API.
I think it's a lot less likely anyone would want the actual responses than the DTOs.

Instead, we could add additional methods explicitly for the responses, like `responses()`, just in case one would need them.
That would obviously need to go into v3, though.

@Sammyjo20 what do you think?

**Comment by Sammyjo20** [comment]
Yes I absolutely agree @juse-less thank you for contributing to this discussion and thank you @boryn for the idea.

I think for the next version of pagination, the `collect` method should always return a collection of DTOs (calling the `createDTOFromResponse` method on the request/connector)

Then we should have `->responses()` which returns an array of responses, or maybe we don't include a method like that at all, because you could just do `$responses = iterator_to_array($paginator)`.

What about people who aren't using Laravel LazyCollections? Should we allow a method like `->data()` or something like that?
