### ISSUE TITLE
Allow sending duplicated keys in multipart body

### ISSUE THREAD

**Issue by bohemima** [Sammyjo20/Saloon#254]
I'm almost done with implementing an API that allows for sending duplicated keys (specifically in a multipart in my case).

Guzzle allows for this using this syntax:

```
    'multipart' => [
        [
            'name'     => 'tag',
            'contents' => 'Tag1'
        ],
        [
            'name'     => 'tag',
            'contents' => 'Tag2'
        ],
        [
            'name'     => 'flattery',
            'contents' => 'Cool library still!'
        ]
    ]
```

Not sure how much of a re-write this is in the library it self, but it seems like keys are used extensively from looking at tests, is this something you have thought about before perhaps?

I guess this could be resolved in multiple ways, allowing value to be an array maybe? `MultipartValue(name: 'tag', value: ['Tag1', 'Tag2'])`, as MultipartBodyRespository seems to rely a lot on keys, perhaps this is a better way than rewriting ?

**Comment by Sammyjo20** [comment]
Hey @bohemima many thanks for posting this and bringing this to my attention. There are always APIs that surprise me! I had assumed (wrongly) that a given name should only appear once. 

Unfortunately, what Saloon does, is it will accept a key-less array, but it will add the keys to the array. The only reason I did this was to support retrieving the data back with `$request->body()->get('tag')`. In my opinion, I don't think we need to key the arrays internally. I can't tell if this is going to be a breaking change or not. I could change the key searching to a better, array-search feature? There's a small chance that people are doing `$request->body()->all()` which will be different, so I think it will be a breaking change.

I'm more than  happy to change this in v3 and onwards, and I'll put it in my list of things to change. In the meantime, a workaround could be to use the config and pass this Guzzle configuration in directly into your request instead of using Saloon's body methods.

In your request class:

```php
protected function defaultConfig(): array
{
    return [
         'multipart' => [
        [
            'name'     => 'tag',
            'contents' => 'Tag1'
        ],
        [
            'name'     => 'tag',
            'contents' => 'Tag2'
        ],
        [
            'name'     => 'flattery',
            'contents' => 'Cool library still!'
        ]
    ];
}
```

Really sorry about this!

**Comment by bohemima** [comment]
No worries, I will give your workaround a try tomorrow, many thanks for pointing it out.

I guess the same issue exist when using defaultQuery since it's an keyed array?

I really like the approach you've taken with Saloon, especially the testability. Keep up the good work!

**Comment by Sammyjo20** [comment]
Thank you ☺️ I’m really glad you like it!

Let me know how it goes with the workaround. Query parameters are the same, yes but I believe Guzzle has the same issue with query parameters.

https://docs.guzzlephp.org/en/stable/request-options.html#query

If you have any issues with query parameters, you can still put query parameters inside of the “defineEndpoint” method on your request.

**Comment by bohemima** [comment]
Workaround confirmed working!

Looks like Guzzle is using `http_build_query` under the hood, which is both good and bad I guess

```
php > var_dump(http_build_query(['Tags' => ['tag1', 'tag2']]));
string(33) "Tags%5B0%5D=tag1&Tags%5B1%5D=tag2"
```

In true PHP fashion brackets are added to array like params but overriding query parameters is more straightforward since we can just add them directly on the endpoint as you wrote as well.

Feel free to close this issue or if you want to keep it open as a reminder for v3 if duplicated keys can be supported for at least Multipart forms.

**Comment by Sammyjo20** [comment]
Thanks for letting me know that it works! I've already noted it down on my todo list so I'll close this PR. Many thanks for the help @bohemima !

**Comment by ManukMinasyan** [comment]
@Sammyjo20 Is this working already? I can't find anything about this in the documentation. Thanks
