### ISSUE TITLE
Custom paginator using callbacks instead of forcing JSON response

### ISSUE THREAD

**Issue by Gummibeer** [Sammyjo20/Saloon#258]
I'm working with non JSON APIs and it was very disappointing that pagination only works for JSON right now.
So I've created a custom paginator resolving things by a custom callback from the first response. That way the user has full control and can use pagination with XML, CSV, HTML or whatever else kind of data formats are used. It's definitely not perfect but I'm, pretty sure that such a callback option would be perfect and could also be implemented in the current paginators and having the current logic as the default closure.

This paginator also allows handling pagination without a known limit/per page beforehand.
So kind of related to #192 with the `$noTotal` config - as both are related to the calculation of the max pages and if there's a next page. This would be solvable if both callbacks can return `null` and there's a `hasMorePages()` or whatever callback.
I mean in the end we have the same situation as with Laravel paginators - there's the paginator and the length-aware paginator.

The paginator would be used like the following:
```php
$paginator = new FirstResponsePagedPaginator(
    connector: $this,
    originalRequest: $request,
    limitCallback: fn (Response $response) => $response->dtoOrFail()->perPage(),
    totalCallback: fn (Response $response) => $response->dtoOrFail()->total(),
);

$paginator->setLimitKeyName('_limit');
$paginator->setPageKeyName('page');
```

```php
<?php

namespace Astrotomic\SourceBansSdk\Paginator;

use Closure;
use Saloon\Contracts\Connector;
use Saloon\Contracts\Request;
use Saloon\Exceptions\PaginatorException;
use Saloon\Http\Paginators\PagedPaginator;

class FirstResponsePagedPaginator extends PagedPaginator
{
    protected ?int $total = null;

    public function __construct(
        Connector $connector,
        Request $originalRequest,
        protected Closure $limitCallback,
        protected Closure $totalCallback,
        int $page = 1
    ) {
        parent::__construct(
            connector: $connector,
            originalRequest: $originalRequest,
            perPage: PHP_INT_MAX,
            page: $page
        );

        $this->limit = null;
    }

    protected function applyPagination(Request $request): void
    {
        if (! is_null($this->currentResponse) && ! is_null($this->limit())) {
            $request->query()->add($this->getLimitKeyName(), $this->limit());
        }

        $request->query()->add($this->getPageKeyName(), $this->getCurrentPage());
    }

    public function limit(): int
    {
        if (is_null($this->currentResponse)) {
            $this->current();
        }

        if (is_null($this->limit)) {
            $this->limit = call_user_func($this->limitCallback, $this->currentResponse);

            if (is_null($this->limit)) {
                throw new PaginatorException('Unable to calculate the limit from the response. Make sure the limit callback is correct.');
            }
        }

        return $this->limit;
    }

    public function totalResults(): int
    {
        if (is_null($this->currentResponse)) {
            $this->current();
        }

        if (is_null($this->total)) {
            $this->total = call_user_func($this->totalCallback, $this->currentResponse);

            if (is_null($this->total)) {
                throw new PaginatorException('Unable to calculate the total results from the response. Make sure the callback key is correct.');
            }
        }

        return $this->total;
    }

    public function totalPages(): int
    {
        return (int) ceil($this->totalResults() / $this->limit());
    }

    protected function isFinished(): bool
    {
        return $this->getCurrentPage() > $this->totalPages();
    }
}
```

**Comment by juse-less** [comment]
Hi!

Apologies for my rambling below. I'm trying to summarise the issues people have found with paginators in v2, as well as possible solutions for v3.
Bear with me. 🙂 

----------
The suggestion of using callbacks is actually how we started.
However, I felt like it wasn't particularly user friendly. At least not for most people.
There were also some caveats and issues with this (see next section around paginator continuation).
Sam helped me refactor that to something we hoped would be more user friendly.
But with all the input in v2, maybe it's something to look back into for v3.

More notably.. paginators were designed around being continuable, so you could save the progress and continue in another process.
Like.. in Laravel you could have a job that requeues itself after a certain amount of requests or time, etc, and then continue were you were.
While the paginators are continuable, I never ended up adding the serialisation needed, because I couldn't figure out a user friendly way of unserialising the data without security issues (PHP's `unserialise()`), or adding a lot of code to mimmic a bit what Laravel does in some places with JsonSerializable.
So removing the continuation thing for v3, should significantly ease things like re-adding callbacks for certain things.
Since we don't really need to think about things like serialisation and unserialisation, that should help a lot at handling custom behaviour through callbacks.
However, I think it's better to have a default callback, that is overwritable using with-ers, rather than providing them through the constructor (or the constructor could get quite large and complex).

----------
In terms of the issue itself, around body types, I think it'd be better to utilise body containers in both requests and responses.
This is something I know me and Sam also discussed a bit. I don't recall why we didn't go with it for responses, though.

However, I think it'd be better to have those body containers that will essentially handle `toArray()` and `toString()`.
That way, we can have a body for JSON, a body for XML, etc.
Since they already know how to serialise and unserialise their own type of data, that logic can kinda be self-contained within the body class/container.

So a client would do something like `request->body()->toString()` for turning the body into a valid string to be sent over the wire.
Subsequently, we can do `response->body()->toArray()` to grab the array representation.
Which would technically allow us to, at least almost, always be able to also do `response->body()->get('some-property')` to get a specific property from the body data.
Which would then subsequently ease things like grabbing the limits, and what not, the same way without having to think about body data type.
It's just a simple `$limit = response->body()->get('limit', default: 250)`.

A side note on that is that the base of this reminds a lot about query parameters- and headers containers.
So maybe the container itself can also be shared between all similar data containers, reducing code to maintain somewhat.

I know I have code for this body-thing somewhere. Let me know if it's of interest and I can try find it. 🙂

**Comment by Sammyjo20** [comment]
Thanks @Gummibeer for your feedback and this is a great suggestion 👍 I hope you don't mind, but to save multiple places I'm going to close this issue here I am going to work on your idea of having default paginators but with the ability to overwrite the classes to resolve various things.
