### ISSUE TITLE
Another method to call requests from connectors?

### ISSUE THREAD

**Issue by Sammyjo20** [Sammyjo20/Saloon#46]
Saloon has given people the option to make requests by calling the request class or using the connector by specifying requests in the $requests property on the connector, but I was thinking of another one:

```php
$connector = new ForgeConnector();

$connector->request(new GetServersRequest); // Init the request but don't send it

$connector->send(new GetServersRequest); // Send the request right away
```

This gives people the ability to define defaults on the connector while not having to register their request and also get
type-hinting in their IDE.

**Comment by Sammyjo20** [comment]
Maybe this should be treated the new "first party" way of sending requests? It allows you to define default data in your constructor like an API token, without needing a keychain.

**Comment by WalrusSoup** [comment]
I think this is ok, but i don't think it's ultimately necessary.

I do see how this is getting a bit complicated, and in the end if kinda feels like code is being moved around and just shifted from place to place. After _really, really thinking about it_, i think the plugin approach is most straight forward and should probably just be titled as the official way to do authorization.

I made an example repo here of how it can be done. The only thing is that it needs a static helper. Given how class based Saloon is I believed that it was possible to keep the same 'cool' syntax approach, but after thinking about it, this solution is the most straight forward, has the least amount of code, and *feels* like the most compatible for everyone. 

Having the token be able to be set on the request possibly felt like it was inconsistent since, typically, authorization headers are sent on all requests which made it feel more appropriate to be in the connector. But i can see a use case for both.

Maybe the final solution for this is just more documentation on the various approaches? But I think that settling on a "best practice is to put it in a plugin" will help portability a lot, then anyone using Saloon will know where authorization will be living without everyone doing their own approach. 

I put an example [repo here](https://github.com/WalrusSoup/saloon-auth) with a test located [here](https://github.com/WalrusSoup/saloon-auth/blob/main/tests/ExampleTest.php)

**Comment by Sammyjo20** [comment]
Hey, thanks for putting this together - that's super helpful so I appreciate it 🤘 I agree. I want to streamline how Saloon works to make it simpler to use. At the end of the day Saloon was born because configuring Guzzle caused a lot of thinking.

My main concern is that people will put something in the constructor of the connector and then when Saloon tries to boot up the connector, it fails because a specific argument is required. Currently this is worked around by doing the following:

```php
Request::make()->setConnector(new MyConnector)->send();
```

I'm going to really think over how I'm going to handle authentication. I think I might change the wording from "keychain" to "credentials" or something a bit more descriptive, then if people choose to, they can create a Saloon Credential class that is just like you have in your example, however it's slightly simpler because people won't have to define their own plugin for it.

With all of this, the idea is that it is optional if people choose to.
