### ISSUE TITLE
Make responses return json by default, without having to call send() method

### ISSUE THREAD

**Issue by ffoods** [Sammyjo20/Saloon#58]
Currently to call a request and have it return json, it looks like this:

`$response = Connector::getTotalRequest('users')->send()->json()`

I want all requests to return json by default, instead of a `SaloonResponse` object, like so:

`$response = Connector::getTotalRequest('users')`

I tried making a custom response, but it enforces that only a `SaloonResponse` object is returned, but even then I still need to call `send()`. How could I achieve this without having to overwrite things?

**Comment by Sammyjo20** [comment]
There isn't a way to make Saloon return JSON every time without overwriting things.

You could overwrite the `__call` and `callStatic `methods but I don't recommend overwriting the SaloonResponse object since there are lots of useful methods used for debugging and not every request will come back successful.
