### ISSUE TITLE
Caching GET requests which has query parameters

### ISSUE THREAD

**Issue by brunolanevik** [Sammyjo20/Saloon#73]
I understand that this can be solved by a custom cache key but I think this should either be changed or clarified in the documentation.

Saloon offers cache requests through the use of the Trait "AlwaysCacheResponses". However by default the cache key is not including the URL query parameters. The documentation states that "By default, the cache key will be built up from the full URL of the request". 

Then the expected behavior should be that the cache key includes the query parameters as a "full URL" according to [RFC 1738](https://datatracker.ietf.org/doc/html/rfc1738#section-3.3) describes a HTTP URL as following:  
An HTTP URL takes the form:

      http://<host>:<port>/<path>?<searchpart>"

**Comment by Sammyjo20** [comment]
Hey @brunolanevik,

That’s a fair point, it’s because internally, Saloon uses Guzzle’s query config option which does not change the request URL. In v2 this method name has been renamed from getFullRequestUrl to getRequestUrl. 

As for the caching though, I can certainly include query parameters as what builds up the default cache key.
